### ISSUE TITLE
Add GHAS Code Scanning to Git Provider Receiver

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#386]
Overview:

The GraphQL query added for GHAS metrics does not include Code Scanning Alerts within the repo. Introduce the code scanning alerts from the repo to the git provider receiver using the rest client. 

The rest api for reference - [https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28)
```[tasklist]
### Tasks
- [x] add pagination to cve graphql query
- [x] add pagination to rest code scanning call
- [x] add code scanning alerts call
- [x] add tests
```
