### ISSUE TITLE
Add branch count metric to the gitlab scraper

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#85]
# Overview

Add the branch count metric to the gitlab scraper

## AC
* docs updated
* scraper is tested
* added functions are tested 
* pageanation works
```[tasklist]
### Tasks
- [x] Update docs
- [ ] Add tests for scraper
- [ ] Add tests for new functions
- [x] Ensure pagination works
```

**Comment by 4lch4** [comment]
- [ ] docs updated
- [ ] scraper is tested
- [ ] added functions are tested
- [x] pagination works
  - Pagination is now working for retrieving projects/repos.
  - Pagination is not necessary for branches as we can request up to `100,000` at a time, which covers most cases.
