### ISSUE TITLE
Contribute second PR for git provider receiver

### ISSUE THREAD

**Issue by pmpaulino** [liatrio/liatrio-otel-collector#99]
# Overview

We need to contribute the git provider receiver to the OTEL contribution repository. This process has already been started with [this issue on the OTEL project](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22028). 

The second PR needs to have core functionality bringing it to a working state.

It may require more than one PR as well to keep them small. 

```[tasklist]
### Tasks
- [x] add functionality to receiver
- [x] add tests and ensure proper test coverage
- [x] create pr
- [x] accept feedback and iterate
```

**Comment by adrielp** [comment]
Waiting on PR approval

**Comment by adrielp** [comment]
Merged & Done
